
# myRSA = RSA()
# inputString = "Hi this is a long testing-string with some gyberish stuff 1234@#$"
# integerOutput = myRSA.convertTextToNumbers(inputString)
# print(integerOutput)
# print()
# print()
# print(myRSA.convertNumberToText(integerOutput))
# pubKey, privateKey = myRSA.generatePublicPrivateKeys(50599,41113)
# print(pubKey)
# print()
# print()
# print(privateKey)
# print()
# print()
# inputNum = 1234
# encryptedNum = myRSA.encrypt(inputNum,pubKey)
# print(encryptedNum)
# print()
# print()
# print(myRSA.decrypt(encryptedNum,privateKey))